cabal-version:  3.0
build-type:     Simple
name:           vector-simple
version:        0.1.0.0
-- don't forget to update the changelog file!
license:        BSD-3-Clause
license-file:   LICENSE
author:         Jaro Reinders <code@jaro.addy.io>
maintainer:     Jaro Reinders <code@jaro.addy.io>
copyright:      (c) Roman Leshchinskiy 2008-2010,
                    Alexey Kuleshevich 2020-2022,
                    Aleksey Khudyakov 2020-2022,
                    Andrew Lelechenko 2020-2022,
                    Jaro Reinders 2026

homepage:       https://github.com/noughtmare/vector-simple
bug-reports:    https://github.com/noughtmare/vector-simple/issues
category:       Data, Data Structures
synopsis:       Simple Efficient Arrays
description:
        An efficient and simple implementation of @Int@-indexed arrays.

        In contrast to vector, the arrays in this package are strict in their
        elements. There is also no fusion framework, so each (safe) operation 
        on immutable vectors yields a fresh copy.


extra-doc-files: changelog.md
                 README.md

source-repository head
  type:     git
  location: https://github.com/noughtmare/vector-simple.git

library
  exposed-modules:  Data.Vector.Grow
                    Data.Vector.Mutable
                    Data.Vector
  build-depends:    base >= 4.18 && < 4.23
                  , data-elevator >= 0.3 && < 0.4
  hs-source-dirs:   src
  default-language: GHC2021
  other-extensions: GADTs
                    MagicHash
                    TypeFamilies
                    UnliftedDatatypes
                    UnboxedTuples
  ghc-options:     -Wall